### ISSUE TITLE
Could not understand audio, waiting for a new phrase...

### ISSUE THREAD

**Issue by mowtschan** [judahpaul16/gpt-home#62]
I'm always getting `Could not understand audio, waiting for a new phrase...` in a loop
I can't get it work, could you point me what am I overlooking?
I tried to collect all info what could help:
1. `arecord -l`
2. `aplay -l`
3. `cat /app/src/common.py | grep alsa_device`
4. `cat /etc/asound.conf`
5. `snippet of event log right after restarting the main app`

**Note**: All commands below I ran inside docker (`docker exec -it gpt-home bash`)

I can record and play sound - no issues: 
```
supervisorctl stop app
arecord -f cd test.wav
aplay test.wav
```

### 1. `arecord -l`
```
**** List of CAPTURE Hardware Devices ****
card 3: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
  ```

### 2. `aplay -l`
```
**** List of PLAYBACK Hardware Devices ****
card 0: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 4: UACDemoV10 [UACDemoV1.0], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

### 3. `cat /app/src/common.py | grep alsa_device`
```
engine.setProperty('alsa_device', 'plughw:3,0')
```

### 4. `cat /etc/asound.conf`
```
# The default PCM (Pulse Code Modulation) device configuration
pcm.!default {
    # 'asym' allows specifying different devices for playback and capture
    type asym
    playback.pcm {
        # 'plug' enables automatic format conversion if necessary
        type plug
        slave.pcm "hw:4,0"  # Sets the playback device to card 4, device 0
    }
    capture.pcm {
        # 'plug' enables automatic format conversion if necessary
        type plug
        slave.pcm "hw:3,0"  # Sets the capture device to card 3, device 0
    }
}

# The default control interface configuration
ctl.!default {
    type hw  # Directly accesses hardware controls
    card 4   # Uses card 4 (USB PnP Audio Device) for control settings
}
```

### 5. `snippet of event log right after restarting the main app`

`docker exec -it gpt-home supervisorctl restart app`
`docker exec -it gpt-home tail -n 100 -f /app/src/events.log`

```
INFO:common:Could not understand audio, waiting for a new phrase...
INFO:common:Could not understand audio, waiting for a new phrase...
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/env/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/env/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/embeddings', 'files': None, 'post_parser': <function Embeddings.create.<locals>.parser at 0x7f9c4feb60>, 'json_data': {'input': ['set an alarm', 'wake me up', 'remind me in', 'play some music', 'next song', 'pause the music', 'play earth wind and fire on Spotify', 'play my playlist', "what's the weather", 'tell me the weather', 'what is the temperature', 'is it going to rain', 'how is the weather in New York', 'turn on the lights', 'switch off the lights', 'dim the lights', 'change the color of the lights', 'set the lights to red', 'schedule a meeting', "what's on my calendar", 'add an event', 'what is left to do today', 'tell me a joke', "what's the time", 'how are you', 'what is the meaning of life', 'what is the capital of France', 'what is the difference between Python 2 and Python 3', 'what is the best programming language', 'who was the first president of the United States', 'what is the largest mammal'], 'model': 'text-embedding-ada-002', 'encoding_format': 'base64'}}
DEBUG:openai._base_client:Sending HTTP Request: POST https://api.openai.com/v1/embeddings
DEBUG:httpcore.connection:connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7fa80c0b50>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f9cad24e0> server_hostname='api.openai.com' timeout=5.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f9c512210>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Sat, 10 Aug 2024 14:28:48 GMT'), (b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'access-control-allow-origin', b'*'), (b'openai-model', b'text-embedding-ada-002'), (b'openai-organization', b'user-2qy0uqllx2tl7v3dib9qj4ns'), (b'openai-processing-ms', b'52'), (b'openai-version', b'2020-10-01'), (b'strict-transport-security', b'max-age=15552000; includeSubDomains; preload'), (b'x-ratelimit-limit-requests', b'3000'), (b'x-ratelimit-limit-tokens', b'1000000'), (b'x-ratelimit-remaining-requests', b'2999'), (b'x-ratelimit-remaining-tokens', b'999832'), (b'x-ratelimit-reset-requests', b'20ms'), (b'x-ratelimit-reset-tokens', b'10ms'), (b'x-request-id', b'req_37ed858dbc6c60410cb5132c6d43aa47'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Set-Cookie', b'__cf_bm=G4IM9hjQypUwY1Pv.HK3vDm5THkd_MSgu_qZ9ZqCaDI-1723300128-1.0.1.1-FPKMhOsrsFRlJEVGtugLhAvNJ8pg5A2oplveum7U2tsvPWUcxVYSYXEfvI2p7bvzkD6U0UDJN5KBBju0Nc7_cQ; path=/; expires=Sat, 10-Aug-24 14:58:48 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'X-Content-Type-Options', b'nosniff'), (b'Set-Cookie', b'_cfuvid=_yVQqsV2BXFJf4meLK5usjkwUCg_1cGy5gh3IlOBY7U-1723300128732-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), (b'Server', b'cloudflare'), (b'CF-RAY', b'8b10acab0d059276-MUC'), (b'Content-Encoding', b'gzip'), (b'alt-svc', b'h3=":443"; ma=86400')])
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:openai._base_client:HTTP Response: POST https://api.openai.com/v1/embeddings "200 OK" Headers([('date', 'Sat, 10 Aug 2024 14:28:48 GMT'), ('content-type', 'application/json'), ('transfer-encoding', 'chunked'), ('connection', 'keep-alive'), ('access-control-allow-origin', '*'), ('openai-model', 'text-embedding-ada-002'), ('openai-organization', 'user-2qy0uqllx2tl7v3dib9qj4ns'), ('openai-processing-ms', '52'), ('openai-version', '2020-10-01'), ('strict-transport-security', 'max-age=15552000; includeSubDomains; preload'), ('x-ratelimit-limit-requests', '3000'), ('x-ratelimit-limit-tokens', '1000000'), ('x-ratelimit-remaining-requests', '2999'), ('x-ratelimit-remaining-tokens', '999832'), ('x-ratelimit-reset-requests', '20ms'), ('x-ratelimit-reset-tokens', '10ms'), ('x-request-id', 'req_37ed858dbc6c60410cb5132c6d43aa47'), ('cf-cache-status', 'DYNAMIC'), ('set-cookie', '__cf_bm=G4IM9hjQypUwY1Pv.HK3vDm5THkd_MSgu_qZ9ZqCaDI-1723300128-1.0.1.1-FPKMhOsrsFRlJEVGtugLhAvNJ8pg5A2oplveum7U2tsvPWUcxVYSYXEfvI2p7bvzkD6U0UDJN5KBBju0Nc7_cQ; path=/; expires=Sat, 10-Aug-24 14:58:48 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), ('x-content-type-options', 'nosniff'), ('set-cookie', '_cfuvid=_yVQqsV2BXFJf4meLK5usjkwUCg_1cGy5gh3IlOBY7U-1723300128732-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None'), ('server', 'cloudflare'), ('cf-ray', '8b10acab0d059276-MUC'), ('content-encoding', 'gzip'), ('alt-svc', 'h3=":443"; ma=86400')])
DEBUG:openai._base_client:request_id: req_37ed858dbc6c60410cb5132c6d43aa47
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:common:Failed to initialize display, skipping...
 Reason: No I2C device at address: 0x3c
Traceback (most recent call last):
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 175, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
  File "/env/lib/python3.11/site-packages/busio.py", line 203, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 52, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/env/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 303, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 181, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
  File "/env/lib/python3.11/site-packages/busio.py", line 193, in readfrom_into
    return self._i2c.readfrom_into(address, buffer, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 59, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 170, in read_bytes
    return self._device.read(number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/common.py", line 118, in initLCD
    display = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_ssd1306.py", line 245, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c, addr)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 62, in __init__
    self.__probe_for_device()
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 184, in __probe_for_device
    raise ValueError("No I2C device at address: 0x%x" % self.device_address)
ValueError: No I2C device at address: 0x3c

DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.google.com:80
DEBUG:urllib3.connectionpool:http://www.google.com:80 "GET / HTTP/1.1" 200 8674
DEBUG:common:Failed to initialize display, skipping...
 Reason: No I2C device at address: 0x3c
Traceback (most recent call last):
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 175, in __probe_for_device
    self.i2c.writeto(self.device_address, b"")
  File "/env/lib/python3.11/site-packages/busio.py", line 203, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 52, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/env/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 303, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 181, in __probe_for_device
    self.i2c.readfrom_into(self.device_address, result)
  File "/env/lib/python3.11/site-packages/busio.py", line 193, in readfrom_into
    return self._i2c.readfrom_into(address, buffer, stop=stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 59, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end - start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/Adafruit_PureIO/smbus.py", line 170, in read_bytes
    return self._device.read(number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/common.py", line 118, in initLCD
    display = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_ssd1306.py", line 245, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c, addr)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 62, in __init__
    self.__probe_for_device()
  File "/env/lib/python3.11/site-packages/adafruit_bus_device/i2c_device.py", line 184, in __probe_for_device
    raise ValueError("No I2C device at address: 0x%x" % self.device_address)
ValueError: No I2C device at address: 0x3c

INFO:common:Timed out, waiting for phrase to start...
INFO:common:Timed out, waiting for phrase to start...
INFO:common:Could not understand audio, waiting for a new phrase...
INFO:common:Could not understand audio, waiting for a new phrase...
INFO:common:Could not understand audio, waiting for a new phrase...
```

**Comment by judahpaul16** [comment]
The logs appear fine. The traceback you see is printed for debug purposes in case you decide not to use an I2C display. Are you speaking the keyword `computer` before stating your phrase? I should probably make that more obvious what the default keyword is. You can change it in the `settings.json` file or web interface. If recording and playing is working fine within the docker container then you should be good to go. Let me know if this helps.

**Comment by mowtschan** [comment]
Yes, the wake word is `computer` but still no luck :-(

the event log just continue looping:
```
INFO:common:Could not understand audio, waiting for a new phrase...
```

<img width="954" alt="image" src="https://github.com/user-attachments/assets/cf94b5b5-2a86-4ac1-bbbd-46d21332aaa9">

**Comment by judahpaul16** [comment]
Hmmm.. what happens if you run `python -m speech_recognition`? You may need to activate the virtual environment first with `source /env/bin/activate` Also what microphone are you using?

**Comment by mowtschan** [comment]
I tried many times and it work ones!!! but some how very very delayed.

**Comment by judahpaul16** [comment]
Interesting. Perhaps internet connection? The code does do an HTTP request to recognize the audio. I wonder if an offline recognizer would solve the delay. It may be less accurate though. You could perhaps try experimenting by replacing `r.recognize_google` in `common.py` to one of the supported recognizers and see how they behave.

[Microsoft Bing Speech](https://azure.microsoft.com/en-us/services/cognitive-services/speech/)
```python
recognize_bing()
```
recognize_google(): [Google Web Speech API](https://w3c.github.io/speech-api/speechapi.html)
recognize_google_cloud(): [Google Cloud Speech](https://cloud.google.com/speech/) - requires installation of the google-cloud-speech package
recognize_houndify(): [Houndify](https://www.houndify.com/) by SoundHound
recognize_ibm(): [IBM Speech to Text](https://www.ibm.com/watson/services/speech-to-text/)
recognize_sphinx(): [CMU Sphinx](https://cmusphinx.github.io/) - requires installing PocketSphinx
recognize_wit(): [Wit.ai](https://wit.ai/)
```

**Comment by mowtschan** [comment]
which one you would recommend as a best one (speed/performance) ?

**Comment by judahpaul16** [comment]
The Google Web Speech API has been performing pretty fine for me as far as speed but I haven't tested on a lot of different networks so people on slower networks may have a difference experience. I did try PocketSphinx but I found the accuracy to be not very good. I haven't tested extensively with the other ones but I'd probably try out Wit.ai
